# Generated by Django 5.0.3 on 2024-04-02 03:26

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('product_exp', models.CharField(choices=[(users.models.PRODUCT_EXP_CHOICES['BEGINNER'], 'Beginner'), (users.models.PRODUCT_EXP_CHOICES['INTERMEDIATE'], 'Intermediate'), (users.models.PRODUCT_EXP_CHOICES['ADVANCED'], 'Advanced')], default='Beginner', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
