# Generated by Django 5.0.3 on 2024-04-04 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_product_exp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='product_exp',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=200),
        ),
    ]
