# Generated by Django 5.0.3 on 2024-04-02 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps_iq', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('app_theme_color', models.CharField(max_length=50)),
                ('app_logo', models.ImageField(upload_to='app_logos/')),
            ],
        ),
    ]
